pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { url 'https://s01.oss.sonatype.org/content/repositories/releases/' }
        maven { url 'https://oss.sonatype.org/content/repositories/releases/' }
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = 'serenity_mobile_base_project'